---
- name: db health check
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Get service facts
      service_facts:

    - name: Check if MongoDB is active
      fail:
        msg: "MongoDB service is not active"
      when: ansible_facts.services['mongod.service'].state != 'running'

