---
- name: terminate db
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: db terminate script send
      copy:
        src: "{{ lookup('env', 'BASE_DIR')}}/ansible/script/dbTerminate.sh"
        dest: /usr/local/sbin
        owner: root
        group: root
        mode: '0755'

    - name: run script
      shell:
        cmd: |
          /usr/local/sbin/dbTerminate.sh

